### PR TITLE
Support for non-hierarchical storage

### PR DESCRIPTION
**Pull request by bezineb5**
Mounts non-hierarchical storage.

Seems to be working well, I tested on a panono camera.

### CODE REVIEW

**Comment by bezineb5** [comment]
I signed it!

**Comment by hanwen** [comment]
can you tell me what type the device says it is?

I want to know what FilesystemType is in 
func (d *StorageInfo) IsHierarchical() bool {
	return d.FilesystemType == FST_GenericHierarchical
}

(https://github.com/hanwen/go-mtpfs/blob/eeb4cce46870f2b57043fca50ea5bc680e72ec8a/mtp/types.go#L119)

**Comment by hanwen** [comment]
lsusb won't tell. You have to send it a GetStorageInfo MTP request. 

The easiest is to add a println to the code snippet I mentioned above.

**Comment by bezineb5** [comment]
Then the answer is "3".
I hope this helps!

**Comment by bezineb5** [comment]
In the light of your remark, I'm going to update my PR to handle the DCF case properly.

**Pull request closed without merging**
